# Generated by Django 3.0.8 on 2020-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default='25.59'),
            preserve_default=False,
        ),
    ]
